### ISSUE TITLE
An error occurs when calling the EpubServer.addEpub (....) method

### ISSUE THREAD

**Issue by javavirys** [readium/r2-streamer-java#16]
W/System.err:     at java.text.DateFormat.parse(DateFormat.java:358)
        at org.readium.r2_streamer.parser.OPFParser.parseOpfFile(OPFParser.java:75)
        at org.readium.r2_streamer.parser.EpubParser.parseEpubFile(EpubParser.java:46)
        at org.readium.r2_streamer.server.EpubServer.parse(EpubServer.java:93)
        at org.readium.r2_streamer.server.EpubServer.addEpub(EpubServer.java:40)

**Comment by javavirys** [comment]
On android 4.1 this error is not present
