### ISSUE TITLE
Not supporting epub

### ISSUE THREAD

**Issue by blennerSilva** [readium/r2-streamer-java#5]
He guys this is my problem:

im getting this log error:

##Log

E/AndroidRuntime: FATAL EXCEPTION: main
Process: com.folioreader.android.sample, PID: 17486
java.lang.RuntimeException: Unable to start activity ComponentInfo{com.folioreader.android.sample/com.folioreader.ui.folio.activity.FolioActivity}: java.lang.NullPointerException: Attempt to read from field 'java.util.List org.readium.r2_streamer.model.publication.EpubPublication.links' on a null object reference
at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2426)
at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:2490)
at android.app.ActivityThread.-wrap11(ActivityThread.java)
at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1354)
at android.os.Handler.dispatchMessage(Handler.java:102)
at android.os.Looper.loop(Looper.java:148)
at android.app.ActivityThread.main(ActivityThread.java:5443)
at java.lang.reflect.Method.invoke(Native Method)
at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:728)
at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:618)
Caused by: java.lang.NullPointerException: Attempt to read from field 'java.util.List org.readium.r2_streamer.model.publication.EpubPublication.links' on a null object reference
at org.readium.r2_streamer.server.EpubServer.addLinks(EpubServer.java:68)
at org.readium.r2_streamer.server.EpubServer.addEpub(EpubServer.java:42)
at com.folioreader.ui.folio.activity.FolioActivity.addEpub(FolioActivity.java:223)
at com.folioreader.ui.folio.activity.FolioActivity.initBook(FolioActivity.java:211)
at com.folioreader.ui.folio.activity.FolioActivity.setupBook(FolioActivity.java:623)
at com.folioreader.ui.folio.activity.FolioActivity.onCreate(FolioActivity.java:161)
at android.app.Activity.performCreate(Activity.java:6245)
at android.app.Instrumentation.callActivityOnCreate(Instrumentation.java:1130)
at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2379)
at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:2490) 
at android.app.ActivityThread.-wrap11(ActivityThread.java) 
at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1354) 
at android.os.Handler.dispatchMessage(Handler.java:102) 
at android.os.Looper.loop(Looper.java:148) 
at android.app.ActivityThread.main(ActivityThread.java:5443) 
at java.lang.reflect.Method.invoke(Native Method) 
at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:728) 
at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:618) 

here are the two examples of books that im using : this first one works

<img width="974" alt="screen shot 2018-01-11 at 18 13 24" src="https://user-images.githubusercontent.com/10924301/34876138-6f552be8-f787-11e7-9ef0-8ea35511c2b4.png">

this one crashes everytime:

<img width="966" alt="screen shot 2018-01-11 at 18 14 03" src="https://user-images.githubusercontent.com/10924301/34876141-7442293a-f787-11e7-928a-e8331085b1f7.png">

as you can se the files are different and i cant launch with this bug can you help me?

**Comment by blennerSilva** [comment]
Updating my issue im getting:
android - org.xml.sax.SAXParseException: Unexpected token (position:TEXT @1:2 in java.io.StringReader@4156ccc8) -

**Comment by rkwright** [comment]
@blennerSilva   Please be aware that we recently (last week) added repos for supporting Kotlin.  As such, we are intending to deprecate and then remove the Java support.  Sorry if this has not been well publicized.

**Comment by hrishikesh-kadam** [comment]
Issue has been fixed in r2-streamer-java v0.1.6 and integrated in FolioReader v0.3.10
@mahavir155 we can close this issue.
